-- 1. 유저 프로필 테이블 (지갑 역할)
create table public.profiles (
  id uuid references auth.users not null primary key,
  nickname text,
  minerals jsonb default '{"gold": 0, "rock": 0}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. 돌(Stone) 데이터 테이블 (돌의 DNA 저장소)
create table public.stones (
  id bigint generated by default as identity primary key,
  owner_id uuid references public.profiles(id) not null,
  dna jsonb not null, -- 예: { "color": "gray", "shape": "round" }
  name text default '이름 없는 돌',
  birth_date timestamp with time zone default timezone('utc'::text, now()) not null,
  level int default 1
);

-- 3. (보너스) 회원가입 시 자동으로 프로필을 만들어주는 마법 (트리거)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, nickname)
  values (new.id, '돌키우기초보');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

------------------------------------------------------------------------


  -- 1. 테이블에 보안 잠금장치 켜기 (이제 규칙 없이는 아무도 못 건드림)
alter table public.profiles enable row level security;
alter table public.stones enable row level security;

-- 2. [프로필] 규칙: "내 정보는 나만 수정, 남들은 보기만 가능"
create policy "프로필은 누구나 볼 수 있음"
on public.profiles for select
using ( true );

create policy "프로필 수정은 본인만"
on public.profiles for update
using ( auth.uid() = id );

-- 3. [돌] 규칙: "돌은 누구나 구경 가능, 키우거나 삭제는 주인만"
create policy "돌 구경은 누구나"
on public.stones for select
using ( true );

create policy "돌 관리는 주인만"
on public.stones for all
using ( auth.uid() = owner_id );

-- 4. (경고 해결) 아까 만든 함수 안전하게 수정
-- (Function Search Path Mutable 경고를 없애줍니다)
alter function public.handle_new_user() set search_path = public;

